// <auto-generated />
using AOAdata.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AOAdata.Migrations
{
    [DbContext(typeof(AOAContext))]
    [Migration("20190927221500_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AOAdata.Models.Part", b =>
                {
                    b.Property<string>("PartNumber")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("PartNumber");

                    b.ToTable("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
